services:
  php74:
    container_name: apivalk-dev-php74
    build:
      context: .
      dockerfile: docker/php74/Dockerfile
    working_dir: /app
    volumes:
      - ./:/app
    command: [ "bash" ]
