<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Contract\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read string $contract_uuid Contract UUID v4
 * @property-read string $invoice_uuid Invoice UUID v4
 */
interface InvoiceUpdatePathShape
{
}