<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Contract\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $due_date
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $created_at
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $amount
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $status
 */
interface InvoiceListSortingShape
{
}