<?php

declare(strict_types=1);

namespace apivalk\apivalk\Tests\PhpUnit\Documentation\DocBlock;

use PHPUnit\Framework\TestCase;
use apivalk\apivalk\Documentation\DocBlock\DocBlockRequest;
use apivalk\apivalk\Documentation\DocBlock\DocBlockShape;

class DocBlockRequestTest extends TestCase
{
    public function testGetters(): void
    {
        $bodyShape = new DocBlockShape('User', 'Body');
        $pathShape = new DocBlockShape('User', 'Path');
        $queryShape = new DocBlockShape('User', 'Query');
        $sortingShape = new DocBlockShape('User', 'Sorting');
        $filteringShape = new DocBlockShape('User', 'Filtering');

        $request = new DocBlockRequest($bodyShape, $pathShape, $queryShape, $sortingShape, $filteringShape, null);

        $this->assertSame($bodyShape, $request->getBodyShape());
        $this->assertSame($pathShape, $request->getPathShape());
        $this->assertSame($queryShape, $request->getQueryShape());
        $this->assertSame($sortingShape, $request->getSortingShape());
        $this->assertSame($filteringShape, $request->getFilteringShape());
    }

    public function testGetRequestDocBlockOnly(): void
    {
        $bodyShape = new DocBlockShape('User', 'Body');
        $pathShape = new DocBlockShape('User', 'Path');
        $queryShape = new DocBlockShape('User', 'Query');
        $sortingShape = new DocBlockShape('User', 'Sorting');
        $filteringShape = new DocBlockShape('User', 'Filtering');

        $request = new DocBlockRequest($bodyShape, $pathShape, $queryShape, $sortingShape, $filteringShape, null);

        $docBlock = $request->getRequestDocBlockOnly('App\\Api\\Shape');

        $this->assertStringContainsString('@generated Auto generated by apivalk', $docBlock);
        $this->assertStringContainsString(
            '@method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\\App\\Api\\Shape\\UserQueryShape query()',
            $docBlock
        );
        $this->assertStringContainsString(
            '@method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\\App\\Api\\Shape\\UserPathShape path()',
            $docBlock
        );
        $this->assertStringContainsString(
            '@method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\\App\\Api\\Shape\\UserBodyShape body()',
            $docBlock
        );
        $this->assertStringContainsString(
            '@method \\App\\Api\\Shape\\UserFilteringShape filtering()',
            $docBlock
        );
        $this->assertStringNotContainsString('paginator()', $docBlock);
    }

    public function testGetRequestDocBlockOnlyWithPaginator(): void
    {
        $bodyShape = new DocBlockShape('User', 'Body');
        $pathShape = new DocBlockShape('User', 'Path');
        $queryShape = new DocBlockShape('User', 'Query');
        $sortingShape = new DocBlockShape('User', 'Sorting');
        $filteringShape = new DocBlockShape('User', 'Filtering');

        $request = new DocBlockRequest(
            $bodyShape,
            $pathShape,
            $queryShape,
            $sortingShape,
            $filteringShape,
            'App\\Api\\UserPaginator'
        );

        $docBlock = $request->getRequestDocBlockOnly('App\\Api\\Shape');

        $this->assertStringContainsString('@method \App\Api\UserPaginator paginator()', $docBlock);
    }

    public function testGetShapeNamespace(): void
    {
        $bodyShape = new DocBlockShape('User', 'Body');
        $pathShape = new DocBlockShape('User', 'Path');
        $queryShape = new DocBlockShape('User', 'Query');
        $sortingShape = new DocBlockShape('User', 'Sorting');
        $filteringShape = new DocBlockShape('User', 'Filtering');

        $request = new DocBlockRequest($bodyShape, $pathShape, $queryShape, $sortingShape, $filteringShape, null);

        $this->assertEquals('App\\Api\\Shape', $request->getShapeNamespace('App\\Api'));
    }

    public function testGetShapeFilenames(): void
    {
        $bodyShape = new DocBlockShape('User', 'Body');
        $pathShape = new DocBlockShape('User', 'Path');
        $queryShape = new DocBlockShape('User', 'Query');
        $sortingShape = new DocBlockShape('User', 'Sorting');
        $filteringShape = new DocBlockShape('User', 'Filtering');

        $request = new DocBlockRequest($bodyShape, $pathShape, $queryShape, $sortingShape, $filteringShape, null);

        $filenames = $request->getShapeFilenames('src/Api');

        $this->assertEquals('src/Api/Shape/UserPathShape.php', $filenames['path']);
        $this->assertEquals('src/Api/Shape/UserQueryShape.php', $filenames['query']);
        $this->assertEquals('src/Api/Shape/UserBodyShape.php', $filenames['body']);
        $this->assertEquals('src/Api/Shape/UserSortingShape.php', $filenames['sorting']);
        $this->assertEquals('src/Api/Shape/UserFilteringShape.php', $filenames['filtering']);
        $this->assertArrayNotHasKey('file', $filenames);
    }

    public function testRequestWithoutFilePropertiesHasNoFileShape(): void
    {
        $request = $this->createRequest(null, new DocBlockShape('User', 'File'));

        $this->assertFalse($request->hasFileShape());
        $this->assertStringNotContainsString('file()', $request->getRequestDocBlockOnly('App\\Api\\Shape'));
    }

    public function testDeclaredFilePropertyAddsTheFileShape(): void
    {
        $fileShape = new DocBlockShape('User', 'File');
        $fileShape->addCustomField('avatar', '\\apivalk\\apivalk\\Http\\Request\\File\\File');

        $request = $this->createRequest(null, $fileShape);

        $this->assertTrue($request->hasFileShape());
        $this->assertSame($fileShape, $request->getFileShape());
        $this->assertStringContainsString(
            '@method \apivalk\apivalk\Http\Request\File\FileBag|\\App\\Api\\Shape\\UserFileShape file()',
            $request->getRequestDocBlockOnly('App\\Api\\Shape')
        );
        $this->assertEquals(
            'src/Api/Shape/UserFileShape.php',
            $request->getShapeFilenames('src/Api')['file']
        );
    }

    private function createRequest(?string $paginatorClass, ?DocBlockShape $fileShape): DocBlockRequest
    {
        return new DocBlockRequest(
            new DocBlockShape('User', 'Body'),
            new DocBlockShape('User', 'Path'),
            new DocBlockShape('User', 'Query'),
            new DocBlockShape('User', 'Sorting'),
            new DocBlockShape('User', 'Filtering'),
            $paginatorClass,
            $fileShape
        );
    }
}
