<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Contract\Request;

/**
 * @generated Auto generated by apivalk
 * @method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\Tests\Integration\RealWorld\Contract\Request\Shape\InvoiceUpdatePathShape path()
 */
class InvoiceUpdateRequest extends \apivalk\apivalk\Http\Request\Resource\ResourceRequest
{
}