<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Request;

/**
 * @generated Auto generated by apivalk
 * @method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\Tests\Integration\RealWorld\Request\Shape\ContractDeletePathShape path()
 */
class ContractDeleteRequest extends \apivalk\apivalk\Http\Request\Resource\ResourceRequest
{
}