<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Request;

/**
 * @generated Auto generated by apivalk
 */
class ContractCreateRequest extends \apivalk\apivalk\Http\Request\Resource\ResourceRequest
{
}