<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Document\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read \apivalk\apivalk\Http\Request\File\File $file
 */
interface DocumentUploadRequestFileShape
{
}
