<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Document\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read string $document_type Document type
 */
interface DocumentUploadRequestBodyShape
{
}
