<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Document\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read int $customer_id Customer integer ID
 */
interface DocumentUploadRequestPathShape
{
}
