<?php

declare(strict_types=1);

namespace apivalk\apivalk\Documentation\DocBlock;

use apivalk\apivalk\Http\Request\Parameter\ParameterBag;
use apivalk\apivalk\Router\Route\Filter\FilterBag;
use apivalk\apivalk\Router\Route\Sort\SortBag;

class DocBlockResourceRequest
{
    /** @var DocBlockShape */
    private $pathShape;
    /** @var DocBlockShape */
    private $sortingShape;
    /** @var DocBlockShape */
    private $filteringShape;
    /** @var string|null */
    private $paginatorClass;
    /** @var string */
    private $baseRequestClass;

    public function __construct(
        DocBlockShape $pathShape,
        DocBlockShape $sortingShape,
        DocBlockShape $filteringShape,
        ?string $paginatorClass,
        string $baseRequestClass
    ) {
        $this->pathShape = $pathShape;
        $this->sortingShape = $sortingShape;
        $this->filteringShape = $filteringShape;
        $this->paginatorClass = $paginatorClass;
        $this->baseRequestClass = $baseRequestClass;
    }

    public function getPathShape(): DocBlockShape
    {
        return $this->pathShape;
    }

    public function getSortingShape(): DocBlockShape
    {
        return $this->sortingShape;
    }

    public function getFilteringShape(): DocBlockShape
    {
        return $this->filteringShape;
    }

    public function getBaseRequestClass(): string
    {
        return $this->baseRequestClass;
    }

    public function getShapeNamespace(string $requestNamespace): string
    {
        return $requestNamespace . '\\Shape';
    }

    /** @return array<string, string> */
    public function getShapeFilenames(string $requestFolder): array
    {
        return [
            'path'      => \sprintf('%s/Shape/%s.php', $requestFolder, $this->pathShape->getClassName()),
            'sorting'   => \sprintf('%s/Shape/%s.php', $requestFolder, $this->sortingShape->getClassName()),
            'filtering' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->filteringShape->getClassName()),
        ];
    }

    public function getDocBlockOnly(string $shapeNamespace): string
    {
        $lines = [];

        if ($this->pathShape->hasProperties()) {
            $lines[] = ' * @method \\' . ParameterBag::class . '|\\' . $shapeNamespace . '\\' . $this->pathShape->getClassName() . ' path()';
        }

        if ($this->sortingShape->hasProperties()) {
            $lines[] = ' * @method \\' . SortBag::class . '|\\' . $shapeNamespace . '\\' . $this->sortingShape->getClassName() . ' sorting()';
        }

        if ($this->filteringShape->hasProperties()) {
            $lines[] = ' * @method \\' . FilterBag::class . '|\\' . $shapeNamespace . '\\' . $this->filteringShape->getClassName() . ' filtering()';
        }

        if ($this->paginatorClass !== null) {
            $lines[] = ' * @method \\' . $this->paginatorClass . ' paginator()';
        }

        array_unshift($lines, ' * @generated Auto generated by apivalk');

        return "/**\n" . implode("\n", $lines) . "\n */";
    }
}
