<?php

declare(strict_types=1);

namespace apivalk\apivalk\Documentation\DocBlock;

class DocBlockRequest
{
    private DocBlockShape $bodyShape;
    private DocBlockShape $pathShape;
    private DocBlockShape $queryShape;
    private DocBlockShape $sortingShape;
    private DocBlockShape $filteringShape;
    private ?string $paginatorClass;
    private ?DocBlockShape $fileShape;
    /** @var DocBlockShape[] */
    private array $filterFieldShapes = [];

    public function __construct(
        DocBlockShape $bodyShape,
        DocBlockShape $pathShape,
        DocBlockShape $queryShape,
        DocBlockShape $sortingShape,
        DocBlockShape $filteringShape,
        ?string $paginatorClass,
        ?DocBlockShape $fileShape = null
    ) {
        $this->bodyShape = $bodyShape;
        $this->pathShape = $pathShape;
        $this->queryShape = $queryShape;
        $this->sortingShape = $sortingShape;
        $this->filteringShape = $filteringShape;
        $this->paginatorClass = $paginatorClass;
        $this->fileShape = $fileShape;
    }

    /**
     * @param DocBlockShape[] $shapes
     */
    public function setFilterFieldShapes(array $shapes): void
    {
        $this->filterFieldShapes = $shapes;
    }

    /** @return DocBlockShape[] */
    public function getFilterFieldShapes(): array
    {
        return $this->filterFieldShapes;
    }

    public function getBodyShape(): DocBlockShape
    {
        return $this->bodyShape;
    }

    public function getPathShape(): DocBlockShape
    {
        return $this->pathShape;
    }

    public function getQueryShape(): DocBlockShape
    {
        return $this->queryShape;
    }

    public function getSortingShape(): DocBlockShape
    {
        return $this->sortingShape;
    }

    public function getFilteringShape(): DocBlockShape
    {
        return $this->filteringShape;
    }

    /** Is only present when the request declares uploaded files. */
    public function getFileShape(): ?DocBlockShape
    {
        return $this->fileShape;
    }

    public function getRequestDocBlockOnly(string $shapeNamespace): string
    {
        $lines = [
            ' * @generated Auto generated by apivalk',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->queryShape->getClassName() . ' query()',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->pathShape->getClassName() . ' path()',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->bodyShape->getClassName() . ' body()',
            ' * @method \\apivalk\\apivalk\\Router\\Route\\Sort\\SortBag|\\' . $shapeNamespace . '\\' . $this->sortingShape->getClassName() . ' sorting()',
            ' * @method \\' . $shapeNamespace . '\\' . $this->filteringShape->getClassName() . ' filtering()',
        ];

        if ($this->hasFileShape()) {
            $lines[] = ' * @method \\apivalk\\apivalk\\Http\\Request\\File\\FileBag|\\' . $shapeNamespace . '\\' . $this->fileShape->getClassName() . ' file()';
        }

        if ($this->paginatorClass !== null) {
            $lines[] = ' * @method \\' . $this->paginatorClass . ' paginator()';
        }

        return "/**\n" . implode("\n", $lines) . "\n */";
    }

    public function getShapeNamespace(string $requestNamespace): string
    {
        return \sprintf('%s\\Shape', $requestNamespace);
    }

    public function getShapeFilenames(string $requestFolder): array
    {
        $filenames = [
            'path' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->pathShape->getClassName()),
            'query' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->queryShape->getClassName()),
            'body' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->bodyShape->getClassName()),
            'sorting' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->sortingShape->getClassName()),
            'filtering' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->filteringShape->getClassName()),
        ];

        // Requests without uploads must not get an empty file shape written next to them.
        if ($this->hasFileShape()) {
            $filenames['file'] = \sprintf('%s/Shape/%s.php', $requestFolder, $this->fileShape->getClassName());
        }

        foreach ($this->filterFieldShapes as $shape) {
            $filenames[$shape->getClassName()] =
                \sprintf('%s/Shape/%s.php', $requestFolder, $shape->getClassName());
        }

        return $filenames;
    }

    public function hasFileShape(): bool
    {
        return $this->fileShape !== null && $this->fileShape->hasProperties();
    }
}
