<?php

declare(strict_types=1);

namespace apivalk\apivalk\Documentation\DocBlock;

use apivalk\apivalk\Documentation\Property\AbstractProperty;

class DocBlockShape
{
    /** @var AbstractProperty[] */
    private array $properties = [];
    /** @var array<string, string> - example: ["status" => array, "message" => string] */
    private array $customFields = [];
    /** @var array<string, string> */
    private array $customFieldDescriptions = [];
    /** @var array<string, string> - example: ["gte()" => "\\DateTime|null"] */
    private array $methods = [];
    private string $type;
    private string $requestName;
    private ?string $extends = null;

    public function __construct(string $requestName, string $type)
    {
        $this->requestName = $requestName;
        $this->type = $type;
    }

    public function addProperty(AbstractProperty $property): void
    {
        $this->properties[] = $property;
    }

    public function addCustomField(string $fieldName, string $fieldType, string $description = ''): void
    {
        $this->customFields[$fieldName] = $fieldType;
        $this->customFieldDescriptions[$fieldName] = $description;
    }

    /**
     * Shapes that describe a filter list methods rather than properties, so that only the
     * operators a field actually declares show up in the IDE.
     */
    /**
     * Lets a generated interface stand in for the bag it describes, so the request
     * docblock can name the shape alone rather than a union with the concrete class.
     */
    public function extendsInterface(string $interface): void
    {
        $this->extends = $interface;
    }

    public function addMethod(string $signature, string $returnType): void
    {
        $this->methods[$signature] = $returnType;
    }

    public function hasProperties(): bool
    {
        return !empty($this->properties) || !empty($this->customFields) || !empty($this->methods);
    }

    public function getClassName(): string
    {
        $className = \sprintf('%s%sShape', \ucfirst($this->requestName), $this->type);

        if (!preg_match('/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$/', $className)) {
            throw new \InvalidArgumentException('Invalid class name: ' . $className);
        }

        return $className;
    }

    public function toString(string $namespace): string
    {
        $namespaceParts = explode('\\', $namespace);
        foreach ($namespaceParts as $part) {
            if (!preg_match('/^[a-zA-Z_\x80-\xff][a-zA-Z0-9_\x80-\xff]*$/', $part)) {
                throw new \InvalidArgumentException(\sprintf('Invalid namespace: %s', $namespace));
            }
        }

        $string = <<<'PHP'
<?php

declare(strict_types=1);

namespace {{NAMESPACE}};

/**
 * @generated Auto generated by apivalk
{{PROPERTIES}}
 */
interface {{CLASS_NAME}}{{EXTENDS}}
{
}
PHP;

        $propertiesString = [];

        foreach ($this->properties as $property) {
            $type = $property->getPhpType();
            if (strpos($type, '\\') !== false && $type[0] !== '\\') {
                $type = '\\' . $type;
            }

            $propertiesString[] = \sprintf(
                '@property-read %s $%s %s',
                $property->isRequired()
                    ? $type
                    : \sprintf('%s|null', $type),
                $property->getPropertyName(),
                $property->getPropertyDescription()
            );
        }

        foreach ($this->customFields as $fieldName => $fieldType) {
            $propertiesString[] = rtrim(\sprintf(
                '@property-read %s $%s %s',
                $fieldType,
                $fieldName,
                $this->customFieldDescriptions[$fieldName] ?? ''
            ));
        }

        foreach ($this->methods as $signature => $returnType) {
            $propertiesString[] = \sprintf('@method %s %s', $returnType, $signature);
        }

        if (empty($propertiesString)) {
            $propertiesBlock = ' * (empty shape)';
        } else {
            $propertiesBlock = ' * ' . implode("\n * ", $propertiesString);
        }

        return str_replace(
            ['{{NAMESPACE}}', '{{CLASS_NAME}}', '{{EXTENDS}}', '{{PROPERTIES}}'],
            [
                $namespace,
                $this->getClassName(),
                $this->extends === null ? '' : ' extends ' . $this->extends,
                $propertiesBlock,
            ],
            $string
        );
    }
}
