<?php

declare(strict_types=1);

namespace apivalk\apivalk\Documentation\DocBlock;

class DocBlockRequest
{
    /** @var DocBlockShape */
    private $bodyShape;
    /** @var DocBlockShape */
    private $pathShape;
    /** @var DocBlockShape */
    private $queryShape;
    /** @var DocBlockShape */
    private $sortingShape;
    /** @var DocBlockShape */
    private $filteringShape;
    /** @var string|null */
    private $paginatorClass;

    public function __construct(
        DocBlockShape $bodyShape,
        DocBlockShape $pathShape,
        DocBlockShape $queryShape,
        DocBlockShape $sortingShape,
        DocBlockShape $filteringShape,
        ?string $paginatorClass
    ) {
        $this->bodyShape = $bodyShape;
        $this->pathShape = $pathShape;
        $this->queryShape = $queryShape;
        $this->sortingShape = $sortingShape;
        $this->filteringShape = $filteringShape;
        $this->paginatorClass = $paginatorClass;
    }

    public function getBodyShape(): DocBlockShape
    {
        return $this->bodyShape;
    }

    public function getPathShape(): DocBlockShape
    {
        return $this->pathShape;
    }

    public function getQueryShape(): DocBlockShape
    {
        return $this->queryShape;
    }

    public function getSortingShape(): DocBlockShape
    {
        return $this->sortingShape;
    }

    public function getFilteringShape(): DocBlockShape
    {
        return $this->filteringShape;
    }

    public function getRequestDocBlockOnly(string $shapeNamespace): string
    {
        $lines = [
            ' * @generated Auto generated by apivalk',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->queryShape->getClassName() . ' query()',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->pathShape->getClassName() . ' path()',
            ' * @method \\apivalk\\apivalk\\Http\\Request\\Parameter\\ParameterBag|\\' . $shapeNamespace . '\\' . $this->bodyShape->getClassName() . ' body()',
            ' * @method \\apivalk\\apivalk\\Router\\Route\\Sort\\SortBag|\\' . $shapeNamespace . '\\' . $this->sortingShape->getClassName() . ' sorting()',
            ' * @method \\apivalk\\apivalk\\Router\\Route\\Filter\\FilterBag|\\' . $shapeNamespace . '\\' . $this->filteringShape->getClassName() . ' filtering()',
        ];

        if ($this->paginatorClass !== null) {
            $lines[] = ' * @method \\' . $this->paginatorClass . ' paginator()';
        }

        return "/**\n" . implode("\n", $lines) . "\n */";
    }

    public function getShapeNamespace(string $requestNamespace): string
    {
        return \sprintf('%s\\Shape', $requestNamespace);
    }

    public function getShapeFilenames(string $requestFolder): array
    {
        return [
            'path' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->pathShape->getClassName()),
            'query' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->queryShape->getClassName()),
            'body' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->bodyShape->getClassName()),
            'sorting' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->sortingShape->getClassName()),
            'filtering' => \sprintf('%s/Shape/%s.php', $requestFolder, $this->filteringShape->getClassName()),
        ];
    }
}
