<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read CustomerListRequestFilterFirstNameShape $first_name
 * @property-read CustomerListRequestFilterLastNameShape $last_name
 * @property-read CustomerListRequestFilterEmailShape $email
 * @property-read CustomerListRequestFilterStatusShape $status
 * @method bool has(string $field)
 * @method \apivalk\apivalk\Router\Route\Filter\FilterInterface|null get(string $field)
 * @method \apivalk\apivalk\Router\Route\Filter\FilterInterface[] all()
 * @method int count()
 */
interface CustomerListRequestFilteringShape extends \IteratorAggregate
{
}