<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read string|null $like Last name, pattern match
 * @method bool has(string $operator)
 * @method string|null raw(string $operator)
 */
interface CustomerListRequestFilterLastNameShape
{
}