<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $title
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $start_date
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $value
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $status
 */
interface ContractListSortingShape
{
}