<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read string $contract_uuid Contract UUID v4
 */
interface ContractUpdatePathShape
{
}