<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Address\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $city
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $country
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $type
 * @property-read \apivalk\apivalk\Router\Route\Sort\Sort $created_at
 */
interface AddressListRequestSortingShape
{
}