<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Address\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read bool|null $equal Is primary, exact match
 * @method bool has(string $operator)
 * @method string|null raw(string $operator)
 */
interface AddressListRequestFilterIsPrimaryShape
{
}