<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Address\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read AddressListRequestFilterCityShape $city
 * @property-read AddressListRequestFilterCountryShape $country
 * @property-read AddressListRequestFilterTypeShape $type
 * @property-read AddressListRequestFilterIsPrimaryShape $is_primary
 * @method bool has(string $field)
 * @method \apivalk\apivalk\Router\Route\Filter\FilterInterface|null get(string $field)
 * @method \apivalk\apivalk\Router\Route\Filter\FilterInterface[] all()
 * @method int count()
 */
interface AddressListRequestFilteringShape extends \IteratorAggregate
{
}