<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Address\Request\Shape;

/**
 * @generated Auto generated by apivalk
 * @property-read int $customer_id Customer integer ID
 * @property-read string $address_uuid Address UUID v4
 */
interface AddressViewRequestPathShape
{
}