<?php

declare(strict_types=1);

namespace Tests\Integration\RealWorld\Customer\Document\Request;

use apivalk\apivalk\Documentation\ApivalkRequestDocumentation;
use apivalk\apivalk\Documentation\Property\EnumProperty;
use apivalk\apivalk\Documentation\Property\FileProperty;
use apivalk\apivalk\Http\Request\AbstractApivalkRequest;

/**
 * @generated Auto generated by apivalk
 * @method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\Tests\Integration\RealWorld\Customer\Document\Request\Shape\DocumentUploadRequestPathShape path()
 * @method \apivalk\apivalk\Http\Request\Parameter\ParameterBag|\Tests\Integration\RealWorld\Customer\Document\Request\Shape\DocumentUploadRequestBodyShape body()
 * @method \apivalk\apivalk\Http\Request\File\FileBag|\Tests\Integration\RealWorld\Customer\Document\Request\Shape\DocumentUploadRequestFileShape file()
 */
class DocumentUploadRequest extends AbstractApivalkRequest
{
    /** @var int */
    public const MAX_SIZE_IN_BYTES = 1024;

    public static function getDocumentation(): ApivalkRequestDocumentation
    {
        $doc = new ApivalkRequestDocumentation();

        $doc->addFileProperty(
            (new FileProperty('file', 'The document to store'))
                ->setMaxSizeInBytes(self::MAX_SIZE_IN_BYTES)
                ->setAllowedMediaTypes(['application/pdf'])
        );
        $doc->addBodyProperty(
            new EnumProperty('document_type', 'Document type', ['invoice', 'contract'])
        );

        return $doc;
    }
}
